version: '3.8'

services:
  p-vue:
    build:
      context: .
      dockerfile: ./root/p-vue/Dockerfile
    ports:
      - "8080:8080"

  p-react:
    build:
      context: .
      dockerfile: ./root/p-react/Dockerfile
    ports:
      - "8081:8081"

  # p-angular:
  #   build:
  #     context: .
  #     dockerfile: ./root/p-angular/Dockerfile
  #   ports:
  #     - "8082:8082"