version: '3.8'

volumes:
  shared-data:
    driver: local

services:
  p-vue:
    build:
      context: .
      dockerfile: ./root/p-vue/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: shared-data
        target: /app

  p-react:
    build:
      context: .
      dockerfile: ./root/p-react/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./root:/root